# https://golangci-lint.run/usage/configuration
version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused
    - misspell
    - nakedret
    - bodyclose
    - gocritic
    - makezero
    - gosec
    - unparam

  exclusions:
    rules:
      - path: _test\.go
        text: "seems to be unused"
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true